version: '3'

services:  
  dev:
    image: node:8.16.2-alpine
  
    working_dir:
      /usr/src/service
  
    ports:
      - ${PORT}:${PORT}

    volumes:
      - .:/usr/src/service
      
    command: npm run test